version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
  # We consume google/transit via a Git submodule.
  - package-ecosystem: gitsubmodule
    directory: '/'
    schedule:
      interval: monthly
