name: test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '14'
          - '16'
          - '18'
          - '20'
          - '22'

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: setup Node v${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install

    - run: npm run build
    - run: npm test
